sudo: false
language: java
jdk:
  - oraclejdk8

notifications:
  email:
    on_success: change
    on_failure: always

# Workaround for https://github.com/travis-ci/travis-ci/issues/4629 , hopefully can be removed some day..
before_install:
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml
